const runId="018f22a0-7b4c-7abc-8def-0123456789ab",callId="018f22a0-7b4c-7abc-8def-0123456789ac",invocationId="018f22a0-7b4c-7000-8000-000000000001";import assert from "node:assert/strict";
import test from "node:test";
import { chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { acquireCurrentPositionV1 } from "../src/assisted-acquisition.ts";
import { createAssistedInvocationTransportV1 } from "../src/assisted-invocation-transport.ts";
import type { AssistedCallConfigV1 } from "../src/assisted-contracts.ts";

async function fixture(role:"judge"|"fixer"="judge",details:unknown|((head:string)=>unknown)={judgeStatus:"escalate",decisionGate:{question:"choose",options:["a","b"]},note:"owner"},termination:"exit0"|"exit7"|"signal"="exit0"){const root=await mkdtemp(join(tmpdir(),"settlement-truth-"));execFileSync("git",["init"],{cwd:root,stdio:"ignore"});execFileSync("git",["config","user.email","t@e"],{cwd:root});execFileSync("git",["config","user.name","T"],{cwd:root});await writeFile(join(root,".gitignore"),".ak/work/\n");execFileSync("git",["add","."],{cwd:root});execFileSync("git",["commit","-m","x"],{cwd:root,stdio:"ignore"});const head=execFileSync("git",["rev-parse","HEAD"],{cwd:root,encoding:"utf8"}).trim();details=typeof details==="function"?details(head):details;const config:AssistedCallConfigV1={version:1,runId,callId,subject:{repositoryRoot:root,github:{owner:"o",name:"r"},parentIssue:28,children:[]},acquisition:{workspaces:[{id:"w",root,relation:"repository"}],evidence:[],labelPolicy:[]},execution:{workspaceId:"w",cwd:root,role,phase:role==="fixer"?"apply":null,environment:{inherit:true,overrides:{},unset:[]},stdin:"inherit"}};const child=join(root,"pi.mjs"),tool=role==="judge"?"ak_judge_output":"ak_fixer_output";await writeFile(child,`#!/usr/bin/env node\nimport{mkdirSync,writeFileSync}from'node:fs';import{join}from'node:path';const a=process.argv,d=a[a.indexOf('--session-dir')+1],id=a[a.indexOf('--session-id')+1],details=${JSON.stringify(details)},tool=${JSON.stringify(tool)};mkdirSync(d,{recursive:true});const t=new Date().toISOString(),rows=[{type:'session',version:3,id,timestamp:t,cwd:process.cwd()},{type:'message',id:'00000001',parentId:null,timestamp:t,message:{role:'assistant',content:[{type:'toolCall',id:'call',name:tool,arguments:details}],api:'test',provider:'test',model:'test',usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:'toolUse',timestamp:Date.now()}},{type:'message',id:'00000002',parentId:'00000001',timestamp:t,message:{role:'toolResult',toolCallId:'call',toolName:tool,content:[{type:'text',text:'accepted'}],isError:false,details,usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},timestamp:Date.now()}}];writeFileSync(join(d,'native_'+id+'.jsonl'),rows.map(JSON.stringify).join('\\n')+'\\n');const termination=${JSON.stringify(termination)};if(termination==='exit7')process.exit(7);if(termination==='signal')process.kill(process.pid,'SIGTERM');`);await chmod(child,0o755);return{root,head,config,child}}
async function invokePostNavigator(f:{root:string;config:AssistedCallConfigV1},position:Awaited<ReturnType<typeof acquireCurrentPositionV1>>,expectedBytes:string){const child=join(f.root,`navigator-${position.snapshot.positionCursor}.mjs`),observed=join(f.root,`observed-${position.snapshot.positionCursor}.txt`);await writeFile(child,`#!/usr/bin/env node\nimport{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{join}from'node:path';const a=process.argv,s=JSON.parse(readFileSync(a[a.indexOf('--ak-navigator-snapshot')+1],'utf8')),d=a[a.indexOf('--session-dir')+1],id=a[a.indexOf('--session-id')+1],item=s.evidence.find(x=>x.id==='settlement:'+s.latestAttempt.invocationId);writeFileSync(${JSON.stringify(observed)},readFileSync(item.handle));mkdirSync(d,{recursive:true});const details={version:1,status:'ordinary',runId:s.runId,subject:s.subject,snapshotDigest:s.digest,positionCursor:s.positionCursor,invocationId:id,latestAttempt:s.latestAttempt,evidenceRead:{},primary:{kind:'stop',reasonCategory:'not_cost_effective',evidenceIds:[],conditions:[],hazards:[]},explanation:'observed post-settlement artifact'};const t=new Date().toISOString(),rows=[{type:'session',version:3,id,timestamp:t,cwd:process.cwd()},{type:'message',id:'00000001',parentId:null,timestamp:t,message:{role:'assistant',content:[{type:'toolCall',id:'call',name:'ak_navigator_output',arguments:details}],api:'test',provider:'test',model:'test',usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:'toolUse',timestamp:Date.now()}},{type:'message',id:'00000002',parentId:'00000001',timestamp:t,message:{role:'toolResult',toolCallId:'call',toolName:'ak_navigator_output',content:[{type:'text',text:'accepted'}],isError:false,details,timestamp:Date.now()}}];writeFileSync(join(d,'native_'+id+'.jsonl'),rows.map(JSON.stringify).join('\\n')+'\\n');`);await chmod(child,0o755);const navId=`018f22a0-7b4c-7000-8000-${String(position.snapshot.positionCursor+20).padStart(12,"0")}`,result=await createAssistedInvocationTransportV1().invokeNavigator({config:f.config,position,invocationId:navId,piArgv:[child]});assert.equal(result.kind,"accepted");if(result.kind==="accepted")assert.deepEqual(result.receipt.latestAttempt,position.snapshot.latestAttempt);assert.equal(await readFile(observed,"utf8"),expectedBytes)}
const deps=(head:string)=>({git:{async observeWorkspace(){return{head,target:head,relation:"repository"as const}}},github:{async repository(){return{id:"R"}},async issue(){return{id:"I",state:"open"as const,labels:[],body:"body",observedAt:"2025-01-01T00:00:00.000Z"}}}});
test("every real selected-role outcome is admitted once as the exact post-settlement artifact",async t=>{const cases=[
  ["judge",{judgeStatus:"converged",note:"done"},"accepted_receipt"],
  ["judge",{judgeStatus:"continue",fix:{summary:"more"},classes:[{name:"Proof",owner:"Runner",boundary:"receipt truth",disposition:"repair"}],note:"continue"},"accepted_receipt"],
  ["judge",{judgeStatus:"escalate",decisionGate:{question:"choose",options:["a","b"]},note:"owner"},"role_escalation"],
  ["judge",{kind:"audit_escalation",conflicts:["authority conflict"],decisionGate:{question:"choose",options:["a","b"]}},"role_escalation"],
  ["fixer",{status:"refused",report:"unsafe",classResults:[{name:"StaleFixerApplyReceiptFixtures",disposition:"refused",remainingScope:"unsafe repair",blocker:{cause:"authority_violation",evidence:"The requested repair is outside the authorized boundary."}}]},"role_refusal"],
]as const;for(const[role,details,terminal]of cases)await t.test(`${role}-${terminal}`,async()=>{const f=await fixture(role,details),transport=createAssistedInvocationTransportV1(),settled=await transport.invokeRole({config:f.config,invocationId,piArgv:[f.child,"--print","task"],beforeTarget:f.head});assert.equal(settled.terminalClass,terminal);const p=await acquireCurrentPositionV1(f.config,1,{invocationId,role,phase:role==="fixer"?"apply":null,beforeTarget:f.head,afterTarget:f.head,terminalClass:settled.terminalClass,reference:settled.reference},deps(f.head)),selected=p.snapshot.evidence.filter(e=>e.id===`settlement:${invocationId}`);assert.equal(selected.length,1);assert.equal(selected[0]!.sha256,settled.reference.sha256);assert.ok(selected[0]!.handle.endsWith(`/evidence/${settled.reference.sha256}`));const artifactBytes=new TextDecoder().decode(p.handles.get(selected[0]!.handle));assert.deepEqual(JSON.parse(artifactBytes).details,details);await invokePostNavigator(f,p,artifactBytes);const recovered=await transport.readCompleted!({config:f.config,invocationId,kind:"role",beforeTarget:f.head});assert.deepEqual(recovered,settled)})});

test("a valid role receipt followed by child failure remains failure live and in recovery",async()=>{for(const [termination,terminal]of [["exit7","infrastructure_failure"],["signal","cancellation"]]as const){const f=await fixture("fixer",(head:string)=>({status:"completed",report:"must not be accepted",classResults:[{name:"StaleFixerApplyReceiptFixtures",disposition:"completed",searchScope:"the fixture repository",exceptions:[],commitSha:head}]}),termination),transport=createAssistedInvocationTransportV1(),live=await transport.invokeRole({config:f.config,invocationId,piArgv:[f.child,"--print","task"],beforeTarget:f.head});assert.equal(live.terminalClass,terminal);assert.ok(live.reference.id.startsWith("failure:"));const recovered=await transport.readCompleted!({config:f.config,invocationId,kind:"role",beforeTarget:f.head});assert.deepEqual(recovered,live);assert.notEqual(live.terminalClass,"accepted_receipt")}});
test("native-session Navigator recovery preserves child nonzero and signal infrastructure truth",async()=>{for(const termination of ["exit7","signal"]as const){const f=await fixture(),position=await acquireCurrentPositionV1(f.config,0,null,deps(f.head)),child=join(f.root,`navigator-${termination}.mjs`);await writeFile(child,`#!/usr/bin/env node\nimport{mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';const a=process.argv,d=a[a.indexOf('--session-dir')+1],id=a[a.indexOf('--session-id')+1],s=JSON.parse(readFileSync(a[a.indexOf('--ak-navigator-snapshot')+1],'utf8')),details={version:1,status:'ordinary',runId:s.runId,subject:s.subject,snapshotDigest:s.digest,positionCursor:s.positionCursor,invocationId:id,latestAttempt:null,evidenceRead:{},primary:{kind:'stop',reasonCategory:'complete',conditions:[],hazards:[],evidenceIds:[]},explanation:'done'},t=new Date().toISOString(),rows=[{type:'session',version:3,id,timestamp:t,cwd:process.cwd()},{type:'message',id:'00000001',parentId:null,timestamp:t,message:{role:'assistant',content:[{type:'toolCall',id:'call',name:'ak_navigator_output',arguments:details}],api:'test',provider:'test',model:'test',usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}},stopReason:'toolUse',timestamp:Date.now()}},{type:'message',id:'00000002',parentId:'00000001',timestamp:t,message:{role:'toolResult',toolCallId:'call',toolName:'ak_navigator_output',content:[{type:'text',text:'accepted'}],isError:false,details,timestamp:Date.now()}}];mkdirSync(d,{recursive:true});writeFileSync(join(d,'native_'+id+'.jsonl'),rows.map(JSON.stringify).join('\\n')+'\\n');${termination==="exit7"?"process.exit(7)":"process.kill(process.pid,'SIGTERM')"};`);await chmod(child,0o755);const transport=createAssistedInvocationTransportV1(),live=await transport.invokeNavigator({config:f.config,position,invocationId,piArgv:[child]});assert.equal(live.kind,"infrastructure_failure");const recovered=await transport.readCompleted!({config:f.config,invocationId,kind:"navigator",beforeTarget:null});assert.deepEqual(recovered,live)}});

test("child failure settles and recovers without a native session or accepted receipt",async()=>{for(const [termination,terminal]of [["exit7","infrastructure_failure"],["signal","cancellation"]]as const){const f=await fixture("fixer"),marker=join(f.root,`spawn-${termination}.txt`),child=join(f.root,`bare-${termination}.mjs`);await writeFile(child,`#!/usr/bin/env node\nimport{appendFileSync}from'node:fs';appendFileSync(${JSON.stringify(marker)},'x');${termination==="exit7"?"process.exit(7)":"process.kill(process.pid,'SIGTERM')"};`);await chmod(child,0o755);const transport=createAssistedInvocationTransportV1(),live=await transport.invokeRole({config:f.config,invocationId,piArgv:[child,"--print","task"],beforeTarget:f.head});assert.equal(live.terminalClass,terminal);assert.equal(live.reference.id,`failure:${invocationId}`);const recovered=await transport.readCompleted!({config:f.config,invocationId,kind:"role",beforeTarget:f.head});assert.deepEqual(recovered,live);assert.equal(await readFile(marker,"utf8"),"x");const childFact=JSON.parse(await readFile(join(f.root,".ak/work/issues/28/assisted",runId,"invocations",invocationId,"child.json"),"utf8"));assert.equal(childFact.exitCode,termination==="exit7"?7:null);assert.equal(childFact.signal,termination==="signal"?"SIGTERM":null)}});

test("exit-zero extraction failure retains child truth for honest recovery",async()=>{const f=await fixture("fixer"),marker=join(f.root,"spawn-exit0.txt"),child=join(f.root,"bare-exit0.mjs");await writeFile(child,`#!/usr/bin/env node\nimport{appendFileSync}from'node:fs';appendFileSync(${JSON.stringify(marker)},'x');`);await chmod(child,0o755);const transport=createAssistedInvocationTransportV1();await assert.rejects(transport.invokeRole({config:f.config,invocationId,piArgv:[child,"--print","task"],beforeTarget:f.head}),/private native session is missing or ambiguous/);assert.deepEqual(JSON.parse(await readFile(join(f.root,".ak/work/issues/28/assisted",runId,"invocations",invocationId,"child.json"),"utf8")),{exitCode:0,signal:null});await assert.rejects(transport.readCompleted!({config:f.config,invocationId,kind:"role",beforeTarget:f.head}),/private native session is missing or ambiguous/);assert.equal(await readFile(marker,"utf8"),"x")});

test("infrastructure and recovered terminal truth retain their exact selected artifact identity",async()=>{for(const terminalClass of ["infrastructure_failure","outcome_unavailable_after_runner_loss"]as const){const f=await fixture(),bytes=`${JSON.stringify({version:1,invocationId,terminalClass})}\n`,failureDir=join(f.root,".ak/work/issues/28/assisted",runId,"invocation-inputs",invocationId);await mkdir(failureDir,{recursive:true});await writeFile(join(failureDir,"failure.json"),bytes);const reference={id:`failure:${invocationId}`,sha256:(await import("../src/sha256.ts")).sha256Hex(bytes)},p=await acquireCurrentPositionV1(f.config,1,{invocationId,role:"judge",phase:null,beforeTarget:f.head,afterTarget:f.head,terminalClass,reference},deps(f.head));const selected=p.snapshot.evidence.filter(e=>e.id===`settlement:${invocationId}`);assert.equal(selected.length,1);assert.equal(selected[0]!.sha256,reference.sha256);assert.equal(new TextDecoder().decode(p.handles.get(selected[0]!.handle)),bytes);await invokePostNavigator(f,p,bytes)}});
