import assert from "node:assert/strict";import test from "node:test";import{access,mkdtemp,mkdir,readFile,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";import{validateAssistedCallConfigV1,validateSelectedPiArgvV1}from"../src/assisted-contracts.ts";import{appendAssistedGenerationV1,AssistedLedgerConflictError,readAssistedLedgerV1}from"../src/assisted-ledger.ts";
import{readAssistedRunV1}from"../src/assisted-runner.ts";import{main as assistedCli}from"../src/assisted-cli.ts";
import{isUuidV7}from"../src/uuidv7.ts";
const id="018f22a0-7b4c-7abc-8def-0123456789ab"; async function config(){const root=await mkdtemp(join(tmpdir(),"assisted-"));await mkdir(join(root,".git"));return{version:1 as const,runId:id,callId:id,subject:{repositoryRoot:root,github:{owner:"acme",name:"widget"},parentIssue:28,children:[]},acquisition:{workspaces:[{id:"main",root,relation:"repository" as const}],evidence:[],labelPolicy:[]},execution:{workspaceId:"main",cwd:root,role:"coder" as const,phase:"apply" as const,environment:{inherit:true,overrides:{},unset:[]},stdin:"inherit" as const}}}
test("public run lookup uses the shared canonical UUIDv7 predicate",async()=>{const root=await mkdtemp(join(tmpdir(),"locator-")),valid="018f22a0-7b4c-7abc-8def-0123456789ab";assert.equal(isUuidV7(valid),true);await assert.rejects(readAssistedRunV1(root,valid),error=>error instanceof Error&&!error.message.includes("invalid assisted run locator"));for(const invalid of [valid.toUpperCase(),"018f22a0-7b4c-6abc-8def-0123456789ab","malformed"]){assert.equal(isUuidV7(invalid),false);await assert.rejects(readAssistedRunV1(root,invalid),/invalid assisted run locator/)}for(const invalidCall of [valid.toUpperCase(),"../../malformed",""]){await assert.rejects(readAssistedRunV1(root,valid,28,invalidCall),/invalid assisted run locator/)}});
test("assisted CLI scopes help before -- and never consumes option tokens as values",async()=>{await assert.rejects(assistedCli(["enter","--config","/definitely/missing.json","--","pi","--help"]),error=>(error as NodeJS.ErrnoException).code==="ENOENT");await assert.rejects(assistedCli(["status","--repository-root","--run-id",id,"--json"]),/missing --repository-root/);await assert.rejects(assistedCli(["status","--repository-root","/tmp","--run-id","--json"]),/missing --run-id/);await assert.rejects(assistedCli(["enter","--config","--run-id","--","pi"]),/missing --config/)});

test("TS and CLI locator rejection precedes filesystem publication",async()=>{const root=await mkdtemp(join(tmpdir(),"locator-effects-")),missing=join(root,".ak");const tsCases:[[unknown,unknown,unknown,unknown],RegExp][]=[[[root,id,0,undefined],/invalid assisted run locator/],[[root,id,1,"../../call"],/invalid assisted run locator/],[[`${root}/x/..`,id,undefined,undefined],/invalid assisted run locator/],[[root,{},undefined,undefined],/invalid assisted run locator/]];for(const [args,error]of tsCases)await assert.rejects(readAssistedRunV1(...args as [string,string,number?,string?]),error);const cliCases=[["status","--repository-root","relative/../root","--run-id",id,"--json"],["status","--repository-root",root,"--run-id","malformed","--json"],["status","--repository-root",root,"--run-id",id,"--call-id","../../call","--json"]];for(const argv of cliCases)await assert.rejects(assistedCli(argv),/invalid assisted run locator/);await assert.rejects(access(missing))});
test("assisted config and one selected Pi role command are closed and agreeing",async()=>{const c=validateAssistedCallConfigV1(await config());assert.deepEqual(validateSelectedPiArgvV1(["pi","--ak-role","coder","--ak-coder-phase","apply","--print","task"],c.execution),["pi","--ak-role","coder","--ak-coder-phase","apply","--print","task"]);assert.throws(()=>validateSelectedPiArgvV1(["sh","-c","pi --ak-role coder"],c.execution));assert.throws(()=>validateSelectedPiArgvV1(["pi","--ak-role","navigator","--print","x"],c.execution));assert.throws(()=>validateSelectedPiArgvV1(["pi","--ak-role","coder","--ak-coder-phase","plan","--print","x"],c.execution));});
test("ledger is append-only hash chained and concurrent generation has one typed loser without deleting peer temporaries",async()=>{const c=validateAssistedCallConfigV1(await config()),dir=join(c.subject.repositoryRoot,".ak/work/issues/28/assisted",id);await appendAssistedGenerationV1(dir,{type:"entered",runId:id,callId:id,positionCursor:0,payload:{subject:c.subject}});const peer=join(dir,"ledger",".tmp-live-peer");await writeFile(peer,"owned by another appender");const settled=await Promise.allSettled([appendAssistedGenerationV1(dir,{type:"ended",runId:id,callId:id,positionCursor:0,payload:{}}),appendAssistedGenerationV1(dir,{type:"ended",runId:id,callId:id,positionCursor:0,payload:{}})]);assert.equal(settled.filter(x=>x.status==="fulfilled").length,1);const loser=settled.find(x=>x.status==="rejected");assert.ok(loser?.status==="rejected"&&loser.reason instanceof AssistedLedgerConflictError);assert.equal(await readFile(peer,"utf8"),"owned by another appender");assert.equal((await readAssistedLedgerV1(dir)).length,2);await writeFile(join(dir,"ledger","0000000004.json"),"{}");await assert.rejects(readAssistedLedgerV1(dir),/gap/);});
