import assert from "node:assert/strict";
import test from "node:test";
import { SessionManager, type ExtensionAPI, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import type { AssistantMessage } from "@earendil-works/pi-ai";
import { createDoctorRoleRuntime, DOCTOR_EVIDENCE_TOOL_NAME, DOCTOR_OUTPUT_TOOL_NAME } from "../src/doctor-role.ts";

const zero = { count: 0, sources: [] }; const patient: any = { version: 1, identity: { issueNumber: 28, runsPath: "/case/.ak/work/issues/28/runs" }, evidence: [], cost: { invocations: zero, legs: zero, modelApiTurns: zero, outputTokens: zero, toolCalls: zero, retries: { ...zero, evidence: "literal run-dir naming" }, statuses: [], commits: [], sessions: [], outputBytes: { ...zero, payload: "raw JSONL bytes", providerWireBytes: "unavailable" } } };
function harness() { const flags = new Map<string, unknown>([["ak-doctor-case", patient.identity.runsPath]]); const tools = new Map<string, any>(); const handlers = new Map<string, any>(); let active: string[] = []; const pi = { registerFlag(name: string, value: unknown) { if (!flags.has(name)) flags.set(name, value); }, getFlag(name: string) { return flags.get(name); }, registerTool(tool: any) { tools.set(tool.name, tool); }, getAllTools() { return ["read", "bash", ...tools.keys()].map((name) => ({ name })); }, setActiveTools(names: string[]) { active = names; }, getActiveTools() { return active; }, on(name: string, fn: any) { handlers.set(name, fn); } }; return { pi, tools, handlers, active: () => active }; }
function context(id: string, abort = () => {}): ExtensionContext { const sessionManager = SessionManager.inMemory(); const message: AssistantMessage = { role: "assistant", content: [{ type: "toolCall", id, name: DOCTOR_OUTPUT_TOOL_NAME, arguments: {} }], api: "openai-responses", provider: "test", model: "test", usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }, stopReason: "toolUse", timestamp: 0 }; sessionManager.appendMessage(message); return { sessionManager, abort } as unknown as ExtensionContext; }
const refusal = { status: "refused", reason: "Session bytes are incomplete.", missingEvidence: [{ need: "session header", targetKeys: ["case"] }] };

test("Doctor activation exposes only paged session evidence and output tools", async () => { const h = harness(); const runtime = createDoctorRoleRuntime(h.pi as ExtensionAPI, { loadSoul: async () => "DOCTOR LAW", loadCase: async () => patient, auditCompliance: async () => ({ status: "pass" }) }, { failInfrastructure(error) { throw error; } }); await runtime.activate(); assert.deepEqual(h.active(), [DOCTOR_EVIDENCE_TOOL_NAME, DOCTOR_OUTPUT_TOOL_NAME]); const prompt = await h.handlers.get("before_agent_start")({ systemPrompt: "BASE" }); assert.match(prompt.systemPrompt, /DOCTOR LAW/); assert.match(prompt.systemPrompt, /issueNumber/); });

test("Doctor output keeps same-model audit and failure behavior", async () => { let decision: "pass" | "revise" | "failure" = "revise"; let aborts = 0; const h = harness(); const runtime = createDoctorRoleRuntime(h.pi as ExtensionAPI, { loadSoul: async () => "DOCTOR LAW", loadCase: async () => patient, async auditCompliance() { if (decision === "failure") throw new Error("provider unavailable"); return decision === "revise" ? { status: "revise", violations: ["missing method proof"] } : { status: "pass" }; } }, { failInfrastructure(error, ctx) { ctx.abort(); throw error; } }); await runtime.activate(); const output = h.tools.get(DOCTOR_OUTPUT_TOOL_NAME); await assert.rejects(output.execute("doctor", refusal, undefined, undefined, context("doctor")), /missing method proof/); decision = "pass"; assert.equal((await output.execute("doctor", refusal, undefined, undefined, context("doctor"))).terminate, true); decision = "failure"; await assert.rejects(output.execute("doctor", refusal, undefined, undefined, context("doctor", () => { aborts++; })), /provider unavailable/); assert.equal(aborts, 1); });
