import assert from "node:assert/strict";
import test from "node:test";
import { Readable, Writable } from "node:stream";
import { AcceptanceCollector } from "../src/recorder/extract.ts";
import { RecorderError } from "../src/recorder/errors.ts";
import { forwardStream, TailRing } from "../src/recorder/spawn.ts";
const details={status:"completed",report:"done"};
const usage={input:1,output:2,cacheRead:0,cacheWrite:0,totalTokens:3,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}};
function packageLifecycleRows(id:string,isError:boolean,args:unknown=details){return [{type:"message",id:`i-${id}`,parentId:null,timestamp:new Date().toISOString(),message:{role:"assistant",content:[{type:"toolCall",id,name:"ak_coder_output",arguments:args}],api:"openai-responses",provider:"openai",model:"model",usage,stopReason:"toolUse",timestamp:Date.now()}},{type:"message",id:`r-${id}`,parentId:`i-${id}`,timestamp:new Date().toISOString(),message:{role:"toolResult",toolCallId:id,toolName:"ak_coder_output",content:[{type:"text",text:isError?"rejected":"Coder report accepted"}],isError,details:args,timestamp:Date.now()}}]}
function collect(rows:ReturnType<typeof packageLifecycleRows>){const collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));return collector.finish(rows.length)}
function invalidIssuance(content:unknown[],mutateMessage?:(message:Record<string,unknown>)=>void){const rows=packageLifecycleRows("mutation",false);const message=rows[0]!.message as Record<string,unknown>;message.content=content;mutateMessage?.(message);const collector=new AcceptanceCollector();assert.throws(()=>rows.forEach((row,index)=>collector.accept(row,index)),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-invalid")}
test("matched rejected attempt may precede the one final accepted result",()=>{const rows=[...packageLifecycleRows("bad",true),...packageLifecycleRows("good",false)],collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));assert.equal(collector.finish(rows.length).receipt.toolCallId,"good")});
test("rejected attempts only are acceptance-missing",()=>{const rows=packageLifecycleRows("bad",true),collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));assert.throws(()=>collector.finish(rows.length),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-missing")});
test("a malformed rejection is acceptance-invalid",()=>{const rows=packageLifecycleRows("bad",true);(rows[1]!.message as Record<string,unknown>).toolCallId="other";const collector=new AcceptanceCollector();assert.throws(()=>rows.forEach((row,index)=>collector.accept(row,index)),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-invalid")});
test("duplicate successful results and successful-then-successful attempts are invalid",()=>{for(const rows of [(()=>{const duplicate=packageLifecycleRows("one",false);duplicate.push(structuredClone(duplicate[1]!));return duplicate})(),[...packageLifecycleRows("one",false),...packageLifecycleRows("two",false)]]){const collector=new AcceptanceCollector();assert.throws(()=>rows.forEach((row,index)=>collector.accept(row,index)),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-invalid")}});
test("nested package lookalikes are inert and no direct lifecycle is missing",()=>{const nested={type:"message",message:{role:"user",content:[{nested:{type:"toolCall",name:"ak_coder_output"}}]}},collector=new AcceptanceCollector();collector.accept(nested,0);assert.throws(()=>collector.finish(1),(error:unknown)=>error instanceof RecorderError&&error.code==="acceptance-missing")});
test("accepted presentation text is not machine state and post-success content is invalid",()=>{const accepted=packageLifecycleRows("accepted",false);((accepted[1]!.message as any).content[0]).text="presentation may change";const collector=new AcceptanceCollector();accepted.forEach((row,index)=>collector.accept(row,index));assert.equal(collector.finish(accepted.length).receipt.toolCallId,"accepted");const trailing=[...packageLifecycleRows("done",false),{type:"message"}],trailingCollector=new AcceptanceCollector();trailing.forEach((row,index)=>trailingCollector.accept(row,index));assert.throws(()=>trailingCollector.finish(trailing.length),(error:unknown)=>error instanceof RecorderError&&error.code==="acceptance-invalid")});
test("thinking siblings and native optional fields are admitted but never projected",()=>{for(const thinking of [[],[{type:"thinking",thinking:"secret"},{type:"thinking",thinking:"redacted",thinkingSignature:"opaque",redacted:true}]]){const rows=packageLifecycleRows("thinking",false);const message=rows[0]!.message as Record<string,unknown>;message.content=[...thinking,{type:"toolCall",id:"thinking",name:"ak_coder_output",arguments:details,thoughtSignature:"opaque-call"}];Object.assign(message,{responseModel:"served-model",responseId:"response-1",diagnostics:[],errorMessage:"",rawStopReason:"tool_calls"});const result=collect(rows);assert.equal(JSON.stringify(result).includes("secret"),false);assert.deepEqual(result.report.hits,[])}});
test("diagnostic details and error are independently absent or records, never present malformed values",()=>{for(const field of ["details","error"] as const){for(const value of [Symbol("absent"),{}]){const rows=packageLifecycleRows(`diagnostic-${field}`,false);const diagnostic:Record<string,unknown>={type:"notice",timestamp:Date.now()};if(typeof value!=="symbol")diagnostic[field]=value;(rows[0]!.message as Record<string,unknown>).diagnostics=[diagnostic];assert.equal(collect(rows).receipt.toolCallId,`diagnostic-${field}`)}for(const malformed of [null,undefined,[],"bad",1])invalidIssuance([{type:"toolCall",id:"mutation",name:"ak_coder_output",arguments:details}],message=>{message.diagnostics=[{type:"notice",timestamp:Date.now(),[field]:malformed}]})}});
test("issuance mutations reject malformed or active siblings",()=>{const call={type:"toolCall",id:"mutation",name:"ak_coder_output",arguments:details};for(const sibling of [{type:"thinking",thinking:"x",thinkingSignature:null},{type:"thinking",thinking:"x",redacted:null},{type:"thinking",thinking:"x",extra:true},{type:"text",text:"x"},{type:"image",data:"x",mimeType:"image/png"},{arbitrary:true},{nested:{type:"toolCall",name:"ak_coder_output"}},{type:"toolCall",id:"other",name:"other_tool",arguments:{}}])invalidIssuance([sibling,call]);invalidIssuance([{type:"thinking",thinking:"x"},call,{...call,id:"second"}]);invalidIssuance([{...call,thoughtSignature:null}]);invalidIssuance([call],message=>{message.responseId=null})});
test("package call IDs are retained exactly without a lexical bound",()=>{const callId=`call_${"x".repeat(200_000)}|fc_${"f".repeat(64)}`,rows=packageLifecycleRows(callId,false),collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));assert.equal(collector.finish(rows.length).receipt.toolCallId,callId)});
test("streaming collector reduces many rejected package payloads before final acceptance",()=>{const collector=new AcceptanceCollector();let index=0;for(let attempt=0;attempt<20_000;attempt++){const rejected=packageLifecycleRows(`rejected-${attempt}`,true,{status:"refused",report:"x".repeat(8_192)});collector.accept(rejected[0],index++);collector.accept(rejected[1],index++)}const lifecycle=packageLifecycleRows("final",false);collector.accept(lifecycle[0],index++);collector.accept(lifecycle[1],index++);assert.equal(collector.finish(index).receipt.toolCallId,"final")});
test("stream forwarding remains bounded beyond 2 GiB logical bytes",async()=>{const chunk=Buffer.alloc(1024*1024,7),count=2049;let bytes=0;const source=Readable.from((function*(){for(let i=0;i<count;i++)yield chunk})());const sink=new Writable({highWaterMark:1024,write(streamChunk,_e,done){bytes+=streamChunk.length;setImmediate(done)}});const ring=new TailRing();await forwardStream(source,sink,ring);assert.equal(bytes,2049*1024*1024);assert.equal(ring.bytes().length,4096);assert.equal(ring.capacity,4096)});
