import assert from "node:assert/strict";
import test from "node:test";
import { Readable, Writable } from "node:stream";
import { execFileSync } from "node:child_process";
import { AcceptanceCollector } from "../src/recorder/extract.ts";
import { RecorderError } from "../src/recorder/errors.ts";
import { forwardStream, TailRing } from "../src/recorder/spawn.ts";
import { reviewerPromptIdentity } from "../src/reviewer-prompt-identity.ts";
import { sha256Hex } from "../src/sha256.ts";
import { compileMechanicalBundle } from "../src/reviewer-construction.ts";
const details={status:"completed",report:"done"};
const usage={input:1,output:2,cacheRead:0,cacheWrite:0,totalTokens:3,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}};
function packageLifecycleRows(id:string,isError:boolean,args:unknown=details){return [{type:"message",id:`i-${id}`,parentId:null,timestamp:new Date().toISOString(),message:{role:"assistant",content:[{type:"toolCall",id,name:"ak_coder_output",arguments:args}],api:"openai-responses",provider:"openai",model:"model",usage,stopReason:"toolUse",timestamp:Date.now()}},{type:"message",id:`r-${id}`,parentId:`i-${id}`,timestamp:new Date().toISOString(),message:{role:"toolResult",toolCallId:id,toolName:"ak_coder_output",content:[{type:"text",text:isError?"rejected":"Coder report accepted"}],isError,details:args,timestamp:Date.now()}}]}
function collect(rows:ReturnType<typeof packageLifecycleRows>){const collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));return collector.finish(rows.length)}
function invalidIssuance(content:unknown[],mutateMessage?:(message:Record<string,unknown>)=>void){const rows=packageLifecycleRows("mutation",false);const message=rows[0]!.message as Record<string,unknown>;message.content=content;mutateMessage?.(message);const collector=new AcceptanceCollector();assert.throws(()=>rows.forEach((row,index)=>collector.accept(row,index)),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-invalid")}
test("matched rejected attempt may precede the one final accepted result",()=>{const rows=[...packageLifecycleRows("bad",true),...packageLifecycleRows("good",false)],collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));assert.equal(collector.finish(rows.length).receipt.toolCallId,"good")});
test("rejected attempts only are acceptance-missing",()=>{const rows=packageLifecycleRows("bad",true),collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));assert.throws(()=>collector.finish(rows.length),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-missing")});
test("a malformed rejection is acceptance-invalid",()=>{const rows=packageLifecycleRows("bad",true);(rows[1]!.message as Record<string,unknown>).toolCallId="other";const collector=new AcceptanceCollector();assert.throws(()=>rows.forEach((row,index)=>collector.accept(row,index)),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-invalid")});
test("duplicate successful results and successful-then-successful attempts are invalid",()=>{for(const rows of [(()=>{const duplicate=packageLifecycleRows("one",false);duplicate.push(structuredClone(duplicate[1]!));return duplicate})(),[...packageLifecycleRows("one",false),...packageLifecycleRows("two",false)]]){const collector=new AcceptanceCollector();assert.throws(()=>rows.forEach((row,index)=>collector.accept(row,index)),(e:unknown)=>e instanceof RecorderError&&e.code==="acceptance-invalid")}});
test("nested package lookalikes are inert and no direct lifecycle is missing",()=>{const nested={type:"message",message:{role:"user",content:[{nested:{type:"toolCall",name:"ak_coder_output"}}]}},collector=new AcceptanceCollector();collector.accept(nested,0);assert.throws(()=>collector.finish(1),(error:unknown)=>error instanceof RecorderError&&error.code==="acceptance-missing")});
test("accepted presentation text is not machine state and post-success content is invalid",()=>{const accepted=packageLifecycleRows("accepted",false);((accepted[1]!.message as any).content[0]).text="presentation may change";const collector=new AcceptanceCollector();accepted.forEach((row,index)=>collector.accept(row,index));assert.equal(collector.finish(accepted.length).receipt.toolCallId,"accepted");const trailing=[...packageLifecycleRows("done",false),{type:"message"}],trailingCollector=new AcceptanceCollector();trailing.forEach((row,index)=>trailingCollector.accept(row,index));assert.throws(()=>trailingCollector.finish(trailing.length),(error:unknown)=>error instanceof RecorderError&&error.code==="acceptance-invalid")});
test("thinking siblings and native optional fields are admitted but never projected",()=>{for(const thinking of [[],[{type:"thinking",thinking:"secret"},{type:"thinking",thinking:"redacted",thinkingSignature:"opaque",redacted:true}]]){const rows=packageLifecycleRows("thinking",false);const message=rows[0]!.message as Record<string,unknown>;message.content=[...thinking,{type:"toolCall",id:"thinking",name:"ak_coder_output",arguments:details,thoughtSignature:"opaque-call"}];Object.assign(message,{responseModel:"served-model",responseId:"response-1",diagnostics:[],errorMessage:"",rawStopReason:"tool_calls"});const result=collect(rows);assert.equal(JSON.stringify(result).includes("secret"),false);assert.deepEqual(result.report.hits,[])}});
test("diagnostic details and error are independently absent or records, never present malformed values",()=>{for(const field of ["details","error"] as const){for(const value of [Symbol("absent"),{}]){const rows=packageLifecycleRows(`diagnostic-${field}`,false);const diagnostic:Record<string,unknown>={type:"notice",timestamp:Date.now()};if(typeof value!=="symbol")diagnostic[field]=value;(rows[0]!.message as Record<string,unknown>).diagnostics=[diagnostic];assert.equal(collect(rows).receipt.toolCallId,`diagnostic-${field}`)}for(const malformed of [null,undefined,[],"bad",1])invalidIssuance([{type:"toolCall",id:"mutation",name:"ak_coder_output",arguments:details}],message=>{message.diagnostics=[{type:"notice",timestamp:Date.now(),[field]:malformed}]})}});
test("issuance mutations reject malformed or active siblings",()=>{const call={type:"toolCall",id:"mutation",name:"ak_coder_output",arguments:details};for(const sibling of [{type:"thinking",thinking:"x",thinkingSignature:null},{type:"thinking",thinking:"x",redacted:null},{type:"thinking",thinking:"x",extra:true},{type:"text",text:"x"},{type:"image",data:"x",mimeType:"image/png"},{arbitrary:true},{nested:{type:"toolCall",name:"ak_coder_output"}},{type:"toolCall",id:"other",name:"other_tool",arguments:{}}])invalidIssuance([sibling,call]);invalidIssuance([{type:"thinking",thinking:"x"},call,{...call,id:"second"}]);invalidIssuance([{...call,thoughtSignature:null}]);invalidIssuance([call],message=>{message.responseId=null})});
test("package call IDs are retained exactly without a lexical bound",()=>{const callId=`call_${"x".repeat(200_000)}|fc_${"f".repeat(64)}`,rows=packageLifecycleRows(callId,false),collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));assert.equal(collector.finish(rows.length).receipt.toolCallId,callId)});
test("streaming collector reduces many rejected package payloads before final acceptance",()=>{const collector=new AcceptanceCollector();let index=0;for(let attempt=0;attempt<20_000;attempt++){const rejected=packageLifecycleRows(`rejected-${attempt}`,true,{status:"refused",report:"x".repeat(8_192)});collector.accept(rejected[0],index++);collector.accept(rejected[1],index++)}const lifecycle=packageLifecycleRows("final",false);collector.accept(lifecycle[0],index++);collector.accept(lifecycle[1],index++);assert.equal(collector.finish(index).receipt.toolCallId,"final")});
function reviewerRows(intent:unknown,receipt:unknown){const rows=packageLifecycleRows("reviewer",false,intent);(rows[0]!.message as any).content[0].name="ak_reviewer_output";(rows[1]!.message as any).toolName="ak_reviewer_output";(rows[1]!.message as any).details=receipt;return rows}
function enrichedReviewerReceipt(status:"completed"|"refused"="completed") { const skill=reviewerPromptIdentity("skill λ\n"),prompt=reviewerPromptIdentity("prompt\n"),text="report λ\n",compiled=compileMechanicalBundle({canonicalSkill:skill.text,task:"task",range:{base:"a",target:"b",diffCommand:"git diff a...b",diffSha256:"1".repeat(64),commits:["b"]},materials:[]});return {version:2,status,...(status==="refused"?{diagnostic:"exact refusal"}:{}),batchIdentity:"batch",reports:{standards:{text,utf8Length:Buffer.byteLength(text),sha256:sha256Hex(text)}},outcomes:{standards:{status:"successful",prompt,workspaceDisposition:"deleted"}},identities:{canonicalSkill:{sha256:skill.sha256,utf8Length:skill.utf8Length,snapshotIdentity:skill},construction:{recipe:"reviewer-common-bundle-v1",bundle:compiled.bundle},target:{repositoryRoot:"/repo",objectFormat:"sha1",targetHead:"b",refs:{"refs/heads/main":{objectId:"b",peeledCommitId:"b"}}}}}}
test("native Reviewer completed and refused intents project to enriched runtime receipts",()=>{for(const status of ["completed","refused"] as const){const intent=status==="completed"?{status}:{status,diagnostic:"exact refusal"};const receipt=enrichedReviewerReceipt(status);const result=collect(reviewerRows(intent,receipt) as ReturnType<typeof packageLifecycleRows>);assert.deepEqual(result.receipt.details,receipt);assert.equal(result.receipt.kind,"reviewer")}});
test("tracked Recorder production artifact projects enriched Reviewer receipts",()=>{const rows=["completed","refused"].map((status)=>{const intent=status==="completed"?{status}:{status,diagnostic:"exact refusal"};return reviewerRows(intent,enrichedReviewerReceipt(status as "completed"|"refused"))});const script=`import {AcceptanceCollector} from './dist/recorder/extract.js';let input='';for await(const chunk of process.stdin)input+=chunk;for(const rows of JSON.parse(input)){const collector=new AcceptanceCollector();rows.forEach((row,index)=>collector.accept(row,index));const result=collector.finish(rows.length);if(result.receipt.kind!=='reviewer'||result.receipt.details.version!==2)process.exit(1)}`;execFileSync(process.execPath,["--input-type=module","--eval",script],{cwd:new URL("..",import.meta.url),input:JSON.stringify(rows)})});
test("native Reviewer projection rejects status, diagnostic, report, and content-identity tampering",()=>{const mutations=[(r:any)=>r.status="refused",(r:any)=>r.reports.standards.utf8Length++, (r:any)=>r.reports.standards.sha256="0".repeat(64),(r:any)=>r.identities.canonicalSkill.snapshotIdentity.text+="tamper",(r:any)=>r.identities.canonicalSkill.snapshotIdentity.sha256="0".repeat(64)];for(const mutate of mutations){const receipt=structuredClone(enrichedReviewerReceipt());mutate(receipt);assert.throws(()=>collect(reviewerRows({status:"completed"},receipt) as ReturnType<typeof packageLifecycleRows>),(error:unknown)=>error instanceof RecorderError&&error.code==="acceptance-invalid")}const refused=enrichedReviewerReceipt("refused");assert.throws(()=>collect(reviewerRows({status:"refused",diagnostic:"different"},refused) as ReturnType<typeof packageLifecycleRows>),(error:unknown)=>error instanceof RecorderError&&error.code==="acceptance-invalid")});
test("stream forwarding remains bounded beyond 2 GiB logical bytes",async()=>{const chunk=Buffer.alloc(1024*1024,7),count=2049;let bytes=0;const source=Readable.from((function*(){for(let i=0;i<count;i++)yield chunk})());const sink=new Writable({highWaterMark:1024,write(streamChunk,_e,done){bytes+=streamChunk.length;setImmediate(done)}});const ring=new TailRing();await forwardStream(source,sink,ring);assert.equal(bytes,2049*1024*1024);assert.equal(ring.bytes().length,4096);assert.equal(ring.capacity,4096)});
