import assert from "node:assert/strict";
import test from "node:test";
import { canonicalSnapshotDigestV1, validateCurrentPositionSnapshotV1, validateNavigatorReceiptV1, navigatorBindingMatchesV1, type CurrentPositionSnapshotV1 } from "../src/navigator-contracts.ts";

const sha = "a".repeat(64), oid = "b".repeat(40), uuid = "018f22a0-7b4c-7abc-8def-0123456789ab";
function snapshot(): CurrentPositionSnapshotV1 {
  const base: Omit<CurrentPositionSnapshotV1,"digest"> = { version:1, capturedAt:"2025-01-01T00:00:00.000Z", runId:uuid, subject:{repositoryRoot:"/repo",github:{owner:"acme",name:"widget",id:"R_1"},parent:{number:28,id:"I_28"}}, children:[{number:29,id:"I_29",relation:"sub_issue",provenance:{kind:"caller",reference:"config"},state:"open",labels:[],observedAt:"2025-01-01T00:00:00.000Z",query:{transport:"github_graphql",operation:"issue"}}], parentObservation:{state:"open",labels:[],observedAt:"2025-01-01T00:00:00.000Z",query:{transport:"github_graphql",operation:"issue"}}, workspaces:[{id:"main",root:"/repo",relation:"repository",head:oid,target:oid}], evidence:[{id:"authority",kind:"authority",sha256:sha,provenance:{kind:"declared",reference:"receipt"},handle:"authority"}], positionCursor:0, latestAttempt:null };
  return {...base,digest:canonicalSnapshotDigestV1(base)};
}
test("snapshot validation is closed, canonical, and exact-child bound",()=>{ const value=snapshot(); assert.deepEqual(validateCurrentPositionSnapshotV1(value),value); assert.throws(()=>validateCurrentPositionSnapshotV1({...value, children:[]})); assert.throws(()=>validateCurrentPositionSnapshotV1({...value, surprise:true})); });
test("Navigator status shapes and binding comparison are exact",()=>{ const s=snapshot(); const receipt=validateNavigatorReceiptV1({version:1,status:"ordinary",runId:s.runId,subject:s.subject,snapshotDigest:s.digest,positionCursor:0,invocationId:uuid,latestAttempt:null,evidenceRead:[{evidenceId:"authority",fullyRead:true}],primary:{kind:"package_role",role:"coder",phase:"apply",evidenceIds:["authority"],conditions:[],hazards:[]},explanation:"Smallest safe step."},s,[{evidenceId:"authority",fullyRead:true}]); assert.equal(navigatorBindingMatchesV1(s,receipt),true); assert.throws(()=>validateNavigatorReceiptV1({...receipt,status:"insufficient"},s,[{evidenceId:"authority",fullyRead:true}])); assert.equal(navigatorBindingMatchesV1({...s,positionCursor:1},receipt),false); const common={...receipt,evidenceRead:[]}; for(const [status,primary] of [["insufficient",{kind:"obtain_evidence_and_reconsult",missing:[{kind:"tracker",identity:"child state"}],evidenceIds:[]}],["refused",{kind:"return_scope_or_authority_defect",defect:{category:"out_of_scope",evidenceId:"authority"},evidenceIds:["authority"]}],["escalated",{kind:"seek_owner_decision",decision:{category:"policy",question:"Choose blast radius."},evidenceIds:[]}]] as const){const reads=status==="refused"?[{evidenceId:"authority",fullyRead:true}]:[];assert.equal(validateNavigatorReceiptV1({...common,status,primary,evidenceRead:reads},s,reads).status,status)} });
