import assert from "node:assert/strict";
import test from "node:test";
import type {ExtensionAPI} from "@earendil-works/pi-coding-agent";
import {createNavigatorRoleRuntime,NAVIGATOR_EVIDENCE_TOOL_NAME,NAVIGATOR_OUTPUT_TOOL_NAME} from "../src/navigator-role.ts";
import {canonicalSnapshotDigestV1} from "../src/navigator-contracts.ts";
import {sha256Hex} from "../src/sha256.ts";
const id="018f22a0-7b4c-7abc-8def-0123456789ab",bytes=new TextEncoder().encode("x"),base={version:1 as const,capturedAt:"2025-01-01T00:00:00.000Z",runId:id,subject:{repositoryRoot:"/r",github:{owner:"o",name:"r",id:"R"},parent:{number:1,id:"I"}},children:[],parentObservation:{state:"open" as const,labels:[],observedAt:"2025-01-01T00:00:00.000Z",query:{transport:"github_rest" as const,operation:"issue"}},labelPolicy:[],workspaces:[{id:"w",root:"/r",relation:"repository" as const,head:"a".repeat(40),target:"a".repeat(40)}],evidence:[{id:"e",kind:"input" as const,sha256:sha256Hex(bytes),provenance:{kind:"declared",reference:"x"},handle:"h"}],positionCursor:0,latestAttempt:null},snapshot={...base,digest:canonicalSnapshotDigestV1(base)};
function harness(failRegistration=0,failVerification=false){const tools=new Map<string,any>();let registrations=0,active:string[]=[];const pi={registerFlag(){},getFlag(){return"snapshot"},registerTool(t:any){registrations++;if(registrations===failRegistration)throw new Error("register");tools.set(t.name,t)},getAllTools(){return[...tools.keys()].map(name=>({name}))},setActiveTools(v:string[]){active=v},getActiveTools(){return failVerification?[NAVIGATOR_EVIDENCE_TOOL_NAME]:active},on(){}};const runtime=createNavigatorRoleRuntime(pi as unknown as ExtensionAPI,{loadSoul:async()=>"LAW",loadSnapshot:async()=>snapshot,loadEvidence:async()=>new Map([["h",bytes]]),auditCompliance:async()=>({status:"pass"})},{failInfrastructure(e){throw e}});return{runtime,tools,active:()=>active,correctVerification(){failVerification=false}}}
for(const nth of [1,2])test(`registration failure ${nth} leaves a complete inert pair and permits corrected activation`,async()=>{const h=harness(nth);await assert.rejects(h.runtime.activate());assert.deepEqual([...h.tools.keys()].sort(),[NAVIGATOR_EVIDENCE_TOOL_NAME,NAVIGATOR_OUTPUT_TOOL_NAME].sort());assert.deepEqual(h.active(),[]);await assert.rejects(h.tools.get(NAVIGATOR_EVIDENCE_TOOL_NAME).execute("x",{evidenceId:"e"}),/not activated/);await h.runtime.activate();assert.deepEqual(h.active(),[NAVIGATOR_EVIDENCE_TOOL_NAME,NAVIGATOR_OUTPUT_TOOL_NAME])});
test("active-tool verification failure is fail-closed and retryable",async()=>{const h=harness(0,true);await assert.rejects(h.runtime.activate(),/narrowing/);assert.deepEqual(h.active(),[]);h.correctVerification();await h.runtime.activate();assert.deepEqual(h.active(),[NAVIGATOR_EVIDENCE_TOOL_NAME,NAVIGATOR_OUTPUT_TOOL_NAME])});
