import assert from "node:assert/strict";
import { chmodSync, closeSync, mkdirSync, openSync, renameSync, symlinkSync, truncateSync, writeFileSync, writeSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { parseRecorderArgv, parseRecorderConfigStructure, type RecorderConfig } from "../src/recorder/config.ts";
import { RecorderError } from "../src/recorder/errors.ts";
import { createSessionLeaf, readSession } from "../src/recorder/session.ts";
import { initGitRepo, makeTempDir } from "./helpers/recorder-test-harness.ts";

const id="018f22e2-7d5a-7abc-8abc-123456789abc", h40="a".repeat(40),h64="b".repeat(64);
function recorderConfigInput(root="/repo"):any{return {version:2,archive:{repositoryRoot:root,root:".ak/dockets",docketId:"issues/33/x"},session:{directory:`.ak/work/${id}/session`,id},execution:{cwd:root,environment:{inherit:true,overrides:{},unset:[]},stdin:"inherit"},declarations:{gitReferences:[{id:"a",repositoryRoot:root,commit:h40,path:"a",blobOid:h40,sha256:h64,kind:"authority"},{id:"t",repositoryRoot:root,commit:h40,path:"t",blobOid:h40,sha256:h64,kind:"task"}],externalInputs:[],exhibits:[]},provenance:{package:null,model:null,target:null}}}
function throws(code:string,fn:()=>unknown){assert.throws(fn,(e:unknown)=>e instanceof RecorderError&&e.code===code)}
test("config v2 is closed at every state-bearing object and rejects v1/noncanonical session identity",()=>{const configInput=recorderConfigInput();configInput.session.extra=true;throws("invalid-config",()=>parseRecorderConfigStructure(JSON.stringify(configInput)));for(const mutate of [(configInput:any)=>configInput.version=1,(configInput:any)=>configInput.session.id=id.toUpperCase(),(configInput:any)=>configInput.session.id="not-uuid",(configInput:any)=>configInput.session.directory=".ak/work/../escape"]){const configInput=recorderConfigInput();mutate(configInput);throws("invalid-config",()=>parseRecorderConfigStructure(JSON.stringify(configInput)))}});
test("Pi argv requires direct executable and exactly one print while forbidding session/machine/reuse flags",()=>{assert.deepEqual(parseRecorderArgv(["--config","c","--","pi","-p","hello"]).childArgv,["pi","-p","hello"]);for(const args of [["-p"],["pi"],["pi","-p","--json"],["pi","--print","--session-dir=x"],["pi","-p","-c"],["pi","-p","--mode=json"],["pi","-p","--no-session"]])throws("invalid-argv",()=>parseRecorderArgv(["--config","c","--",...args]))});
function fixture(){const root=makeTempDir("session-integrity-");initGitRepo(root);mkdirSync(join(root,".ak/work/x"),{recursive:true});const config=recorderConfigInput(root) as RecorderConfig;config.session.directory=".ak/work/x/session";config.execution.cwd=root;const owner=createSessionLeaf(config);return{root,config,owner,path:owner.path,main:join(owner.path,`2026-01-01_${id}.jsonl`)}}
const header=(cwd:string,extra:Record<string,unknown>={})=>({type:"session",version:3,id,timestamp:"2026-01-01T00:00:00.000Z",cwd,...extra});
function writeMainSessionRows(sessionFixture:ReturnType<typeof fixture>,rows:unknown[],newline=true){writeFileSync(sessionFixture.main,rows.map(row=>JSON.stringify(row)).join("\n")+(newline?"\n":""))}
test("session leaf is exclusive private and rejects symlink ancestors",()=>{const sessionFixture=fixture();assert.equal((sessionFixture.owner.dev>0),true);throws("session-collision",()=>createSessionLeaf(sessionFixture.config));const root=makeTempDir("session-link-");initGitRepo(root);mkdirSync(join(root,"outside"));mkdirSync(join(root,".ak"));symlinkSync(join(root,"outside"),join(root,".ak/work"));const config=recorderConfigInput(root) as RecorderConfig;config.session.directory=".ak/work/x/session";throws("session-collision",()=>createSessionLeaf(config))});
test("inventory admits one main and flat regular reviewer legs only",()=>{for(const shape of ["zero","multiple","extra","top-symlink","leg-symlink","leg-nested"]){const sessionFixture=fixture();if(shape!=="zero")writeMainSessionRows(sessionFixture,[header(sessionFixture.root)]);if(shape==="multiple")writeFileSync(join(sessionFixture.path,`other_${id}.jsonl`),"x\n");if(shape==="extra")writeFileSync(join(sessionFixture.path,"extra"),"x");if(shape==="top-symlink")symlinkSync(sessionFixture.main,join(sessionFixture.path,"alias"));if(shape.startsWith("leg-")){mkdirSync(join(sessionFixture.path,"reviewer-legs"));shape==="leg-symlink"?symlinkSync(sessionFixture.main,join(sessionFixture.path,"reviewer-legs/x.jsonl")):mkdirSync(join(sessionFixture.path,"reviewer-legs/nested"));}throws(shape==="zero"?"session-missing":"session-ambiguous",()=>readSession(sessionFixture.config,sessionFixture.owner))}const sessionFixture=fixture();writeMainSessionRows(sessionFixture,[header(sessionFixture.root)]);mkdirSync(join(sessionFixture.path,"reviewer-legs"));writeFileSync(join(sessionFixture.path,"reviewer-legs/a.jsonl"),"raw\n");assert.equal(readSession(sessionFixture.config,sessionFixture.owner).basename.endsWith(`_${id}.jsonl`),true)});
test("Pi v3 stream rejects missing/extra header fields, malformed rows, chain errors and truncation",()=>{const cases:unknown[][]=[[ ],[header("wrong")],[header("ROOT",{parentSession:null})],[header("ROOT"),"nonobject"],[header("ROOT"),{type:"message",id:"00000001",parentId:"wrong",timestamp:"2026-01-01T00:00:00.000Z"}],[header("ROOT"),{type:"message",id:"00000001",parentId:null,timestamp:null}],[header("ROOT"),{type:"message",id:"00000001",parentId:null,timestamp:"2026-01-01T00:00:00.000Z"},{type:"message",id:"00000001",parentId:"00000001",timestamp:"2026-01-01T00:00:00.000Z"}],[header("ROOT"),header("ROOT")]];for(const rows of cases){const sessionFixture=fixture();writeMainSessionRows(sessionFixture,rows.map(r=>r&&typeof r==="object"&&"cwd" in (r as any)?{...(r as any),cwd:(r as any).cwd==="ROOT"?sessionFixture.root:(r as any).cwd}:r));throws("session-corrupt",()=>readSession(sessionFixture.config,sessionFixture.owner))}const sessionFixture=fixture();writeFileSync(sessionFixture.main,"{bad}\n");throws("session-corrupt",()=>readSession(sessionFixture.config,sessionFixture.owner));const unterminatedSessionFixture=fixture();writeMainSessionRows(unterminatedSessionFixture,[header(unterminatedSessionFixture.root)],false);throws("session-corrupt",()=>readSession(unterminatedSessionFixture.config,unterminatedSessionFixture.owner))});
test("native row IDs retain exact admitted 8-hex and canonical UUID identities",()=>{const sessionFixture=fixture(),uuid="12345678-1234-4234-9234-123456789abc";writeMainSessionRows(sessionFixture,[header(sessionFixture.root),{type:"message",id:"abcdef01",parentId:null,timestamp:"2026-01-01T00:00:00.000Z"},{type:"message",id:uuid,parentId:"abcdef01",timestamp:"2026-01-01T00:00:00.000Z"}]);const ids:string[]=[];readSession(sessionFixture.config,sessionFixture.owner,(row,index)=>{if(index>0)ids.push((row as {id:string}).id)});assert.deepEqual(ids,["abcdef01",uuid]);for(const invalid of ["abcdef0","ABCDEF01","x".repeat(1024)]){const bad=fixture();writeMainSessionRows(bad,[header(bad.root),{type:"message",id:invalid,parentId:null,timestamp:"2026-01-01T00:00:00.000Z"}]);throws("session-corrupt",()=>readSession(bad.config,bad.owner))}});
test("streamed JSONL enforces the exact 16 MiB newline-inclusive boundary",()=>{const limit=16*1024*1024;for(const delta of [0,1]){const sessionFixture=fixture();const prefix=JSON.stringify(header(sessionFixture.root))+"\n";const skeleton={type:"message",id:"00000001",parentId:null,timestamp:"2026-01-01T00:00:00.000Z",payload:""};const fixed=Buffer.byteLength(JSON.stringify(skeleton));const payloadLength=limit+delta-1-fixed;const line=JSON.stringify({...skeleton,payload:"x".repeat(payloadLength)});assert.equal(Buffer.byteLength(line)+1,limit+delta);writeFileSync(sessionFixture.main,prefix+line+"\n");if(delta===0)assert.equal(readSession(sessionFixture.config,sessionFixture.owner).rowCount,2);else throws("session-corrupt",()=>readSession(sessionFixture.config,sessionFixture.owner))}});
test("streamed JSONL enforces the exact 100000-entry boundary",()=>{for(const count of [100000,100001]){const sessionFixture=fixture();const fd=openSync(sessionFixture.main,"w");try{writeSync(fd,JSON.stringify(header(sessionFixture.root))+"\n");let parent:null|string=null;for(let i=1;i<count;i++){const id=i.toString(16).padStart(8,"0");writeSync(fd,JSON.stringify({type:"message",id,parentId:parent,timestamp:"2026-01-01T00:00:00.000Z"})+"\n");parent=id}}finally{closeSync(fd)}if(count===100000)assert.equal(readSession(sessionFixture.config,sessionFixture.owner).rowCount,count);else throws("session-corrupt",()=>readSession(sessionFixture.config,sessionFixture.owner))}});
test("bound snapshot detects replacement, growth, shrink, metadata and inventory mutation",()=>{for(const kind of ["replace","grow","shrink","metadata","inventory"]){const sessionFixture=fixture();writeMainSessionRows(sessionFixture,[header(sessionFixture.root)]);const s=readSession(sessionFixture.config,sessionFixture.owner);if(kind==="replace"){const p=sessionFixture.main+".new";writeFileSync(p,"x\n");renameSync(p,sessionFixture.main)}else if(kind==="grow")writeFileSync(sessionFixture.main,Buffer.concat([Buffer.from(JSON.stringify(header(sessionFixture.root))+"\n"),Buffer.from("x") ]));else if(kind==="shrink")truncateSync(sessionFixture.main,1);else if(kind==="metadata")chmodSync(sessionFixture.main,0o600);else writeFileSync(join(sessionFixture.path,"extra"),"x");throws("session-modified",s.verify)}});
