import assert from "node:assert/strict";
import { chmodSync, closeSync, mkdirSync, openSync, renameSync, symlinkSync, truncateSync, writeFileSync, writeSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { parseRecorderArgv, parseRecorderConfigStructure, type RecorderConfig } from "../src/recorder/config.ts";
import { RecorderError } from "../src/recorder/errors.ts";
import { createSessionLeaf, readSession } from "../src/recorder/session.ts";
import { initGitRepo, makeTempDir } from "./helpers/recorder-test-harness.ts";

const id="018f22e2-7d5a-7abc-8abc-123456789abc", h40="a".repeat(40),h64="b".repeat(64);
function raw(root="/repo"):any{return {version:2,archive:{repositoryRoot:root,root:".ak/dockets",docketId:"issues/33/x"},session:{directory:`.ak/work/${id}/session`,id},execution:{cwd:root,environment:{inherit:true,overrides:{},unset:[]},stdin:"inherit"},declarations:{gitReferences:[{id:"a",repositoryRoot:root,commit:h40,path:"a",blobOid:h40,sha256:h64,kind:"authority"},{id:"t",repositoryRoot:root,commit:h40,path:"t",blobOid:h40,sha256:h64,kind:"task"}],externalInputs:[],exhibits:[]},provenance:{package:null,model:null,target:null}}}
function throws(code:string,fn:()=>unknown){assert.throws(fn,(e:unknown)=>e instanceof RecorderError&&e.code===code)}
test("config v2 is closed at every state-bearing object and rejects v1/noncanonical session identity",()=>{const x=raw();x.session.extra=true;throws("invalid-config",()=>parseRecorderConfigStructure(JSON.stringify(x)));for(const mutate of [(x:any)=>x.version=1,(x:any)=>x.session.id=id.toUpperCase(),(x:any)=>x.session.id="not-uuid",(x:any)=>x.session.directory=".ak/work/../escape"]){const x=raw();mutate(x);throws("invalid-config",()=>parseRecorderConfigStructure(JSON.stringify(x)))}});
test("Pi argv requires direct executable and exactly one print while forbidding session/machine/reuse flags",()=>{assert.deepEqual(parseRecorderArgv(["--config","c","--","pi","-p","hello"]).childArgv,["pi","-p","hello"]);for(const args of [["-p"],["pi"],["pi","-p","--json"],["pi","--print","--session-dir=x"],["pi","-p","-c"],["pi","-p","--mode=json"],["pi","-p","--no-session"]])throws("invalid-argv",()=>parseRecorderArgv(["--config","c","--",...args]))});
function fixture(){const root=makeTempDir("session-integrity-");initGitRepo(root);mkdirSync(join(root,".ak/work/x"),{recursive:true});const c=raw(root) as RecorderConfig;c.session.directory=".ak/work/x/session";c.execution.cwd=root;const owner=createSessionLeaf(c);return{root,c,owner,path:owner.path,main:join(owner.path,`2026-01-01_${id}.jsonl`)}}
const header=(cwd:string,extra:Record<string,unknown>={})=>({type:"session",version:3,id,timestamp:"2026-01-01T00:00:00.000Z",cwd,...extra});
function put(f:ReturnType<typeof fixture>,rows:unknown[],newline=true){writeFileSync(f.main,rows.map(x=>JSON.stringify(x)).join("\n")+(newline?"\n":""))}
test("session leaf is exclusive private and rejects symlink ancestors",()=>{const f=fixture();assert.equal((f.owner.dev>0),true);throws("session-collision",()=>createSessionLeaf(f.c));const root=makeTempDir("session-link-");initGitRepo(root);mkdirSync(join(root,"outside"));mkdirSync(join(root,".ak"));symlinkSync(join(root,"outside"),join(root,".ak/work"));const c=raw(root) as RecorderConfig;c.session.directory=".ak/work/x/session";throws("session-collision",()=>createSessionLeaf(c))});
test("inventory admits one main and flat regular reviewer legs only",()=>{for(const shape of ["zero","multiple","extra","top-symlink","leg-symlink","leg-nested"]){const f=fixture();if(shape!=="zero")put(f,[header(f.root)]);if(shape==="multiple")writeFileSync(join(f.path,`other_${id}.jsonl`),"x\n");if(shape==="extra")writeFileSync(join(f.path,"extra"),"x");if(shape==="top-symlink")symlinkSync(f.main,join(f.path,"alias"));if(shape.startsWith("leg-")){mkdirSync(join(f.path,"reviewer-legs"));shape==="leg-symlink"?symlinkSync(f.main,join(f.path,"reviewer-legs/x.jsonl")):mkdirSync(join(f.path,"reviewer-legs/nested"));}throws(shape==="zero"?"session-missing":"session-ambiguous",()=>readSession(f.c,f.owner))}const f=fixture();put(f,[header(f.root)]);mkdirSync(join(f.path,"reviewer-legs"));writeFileSync(join(f.path,"reviewer-legs/a.jsonl"),"raw\n");assert.equal(readSession(f.c,f.owner).basename.endsWith(`_${id}.jsonl`),true)});
test("Pi v3 stream rejects missing/extra header fields, malformed rows, chain errors and truncation",()=>{const cases:unknown[][]=[[ ],[header("wrong")],[header("ROOT",{parentSession:null})],[header("ROOT"),"nonobject"],[header("ROOT"),{type:"message",id:"00000001",parentId:"wrong"}],[header("ROOT"),{type:"message",id:"00000001",parentId:null},{type:"message",id:"00000001",parentId:"00000001"}],[header("ROOT"),header("ROOT")]];for(const rows of cases){const f=fixture();put(f,rows.map(r=>r&&typeof r==="object"&&"cwd" in (r as any)?{...(r as any),cwd:(r as any).cwd==="ROOT"?f.root:(r as any).cwd}:r));throws("session-corrupt",()=>readSession(f.c,f.owner))}const f=fixture();writeFileSync(f.main,"{bad}\n");throws("session-corrupt",()=>readSession(f.c,f.owner));const g=fixture();put(g,[header(g.root)],false);throws("session-corrupt",()=>readSession(g.c,g.owner))});
test("native row IDs retain exact admitted 8-hex and canonical UUID identities",()=>{const f=fixture(),uuid="12345678-1234-4234-9234-123456789abc";put(f,[header(f.root),{type:"message",id:"abcdef01",parentId:null},{type:"message",id:uuid,parentId:"abcdef01"}]);const ids:string[]=[];readSession(f.c,f.owner,(row,index)=>{if(index>0)ids.push((row as {id:string}).id)});assert.deepEqual(ids,["abcdef01",uuid]);for(const invalid of ["abcdef0","ABCDEF01","x".repeat(1024)]){const bad=fixture();put(bad,[header(bad.root),{type:"message",id:invalid,parentId:null}]);throws("session-corrupt",()=>readSession(bad.c,bad.owner))}});
test("streamed JSONL enforces the exact 16 MiB newline-inclusive boundary",()=>{const limit=16*1024*1024;for(const delta of [0,1]){const f=fixture();const prefix=JSON.stringify(header(f.root))+"\n";const skeleton={type:"message",id:"00000001",parentId:null,payload:""};const fixed=Buffer.byteLength(JSON.stringify(skeleton));const payloadLength=limit+delta-1-fixed;const line=JSON.stringify({...skeleton,payload:"x".repeat(payloadLength)});assert.equal(Buffer.byteLength(line)+1,limit+delta);writeFileSync(f.main,prefix+line+"\n");if(delta===0)assert.equal(readSession(f.c,f.owner).rowCount,2);else throws("session-corrupt",()=>readSession(f.c,f.owner))}});
test("streamed JSONL enforces the exact 100000-entry boundary",()=>{for(const count of [100000,100001]){const f=fixture();const fd=openSync(f.main,"w");try{writeSync(fd,JSON.stringify(header(f.root))+"\n");let parent:null|string=null;for(let i=1;i<count;i++){const id=i.toString(16).padStart(8,"0");writeSync(fd,JSON.stringify({type:"message",id,parentId:parent})+"\n");parent=id}}finally{closeSync(fd)}if(count===100000)assert.equal(readSession(f.c,f.owner).rowCount,count);else throws("session-corrupt",()=>readSession(f.c,f.owner))}});
test("bound snapshot detects replacement, growth, shrink, metadata and inventory mutation",()=>{for(const kind of ["replace","grow","shrink","metadata","inventory"]){const f=fixture();put(f,[header(f.root)]);const s=readSession(f.c,f.owner);if(kind==="replace"){const p=f.main+".new";writeFileSync(p,"x\n");renameSync(p,f.main)}else if(kind==="grow")writeFileSync(f.main,Buffer.concat([Buffer.from(JSON.stringify(header(f.root))+"\n"),Buffer.from("x") ]));else if(kind==="shrink")truncateSync(f.main,1);else if(kind==="metadata")chmodSync(f.main,0o600);else writeFileSync(join(f.path,"extra"),"x");throws("session-modified",s.verify)}});
