import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { materializeMechanicalBundle } from "../src/reviewer-bundle-materializer.ts";
import { compileMechanicalBundle, type PinnedMechanicalBundleV1 } from "../src/reviewer-construction.ts";
import { withPrimaryAwareCleanup } from "./helpers/primary-aware-cleanup.ts";
const make=()=>compileMechanicalBundle({canonicalSkill:"skill\n",task:"task\n",range:{base:"A",target:"B",diffCommand:"git diff A...B",diffSha256:"1".repeat(64),commits:["B"]},materials:[{id:"m",repositoryPath:"M.md",text:"material\n",sha256:"2".repeat(64)}]}).bundle;
async function root(){return mkdtemp(join(tmpdir(),"bundle-test-"));}
test("materializer installs exact common bundle and verifies readback",async()=>{const r=await root();await withPrimaryAwareCleanup(async()=>{const b=make();const e=await materializeMechanicalBundle(r,"standards",b);assert.equal(e.entries.every(x=>x.verified),true);for(const x of b.entries)assert.equal(await readFile(join(r,x.relativeClonePath),"utf8"),x.bytes);},()=>rm(r,{recursive:true,force:true}));});
test("materializer rejects digest and manifest mutation atomically",async()=>{for(const mutate of [(b:PinnedMechanicalBundleV1)=>({...b,manifestSha256:"0".repeat(64)}),(b:PinnedMechanicalBundleV1)=>({...b,entries:[{...b.entries[0]!,bytes:"changed"},...b.entries.slice(1)]})]){const r=await root();await withPrimaryAwareCleanup(()=>assert.rejects(materializeMechanicalBundle(r,"standards",mutate(make()) as PinnedMechanicalBundleV1)),()=>rm(r,{recursive:true,force:true}));}});
test("materializer rejects traversal, absolute paths, collisions, and symlink parents",async()=>{for(const path of ["../escape","/absolute",".ak-reviewer/materials/../escape"]){const r=await root();const b=make();await withPrimaryAwareCleanup(()=>assert.rejects(materializeMechanicalBundle(r,"standards",{...b,entries:[{...b.entries[0]!,relativeClonePath:path}]})),()=>rm(r,{recursive:true,force:true}));}const r=await root();await withPrimaryAwareCleanup(async()=>{await mkdir(join(r,"outside"));await mkdir(join(r,".ak-reviewer"));await symlink(join(r,"outside"),join(r,".ak-reviewer","materials"));await assert.rejects(materializeMechanicalBundle(r,"spec",make()),/symlink|collision|manifest|confined/i);},()=>rm(r,{recursive:true,force:true}));});
test("existing destination collision does not overwrite reviewed clone content",async()=>{const r=await root();await withPrimaryAwareCleanup(async()=>{const b=make();const p=join(r,b.entries[0]!.relativeClonePath);await mkdir(join(p,".."),{recursive:true});await writeFile(p,"owned\n");await assert.rejects(materializeMechanicalBundle(r,"standards",b),/collision/);assert.equal(await readFile(p,"utf8"),"owned\n");},()=>rm(r,{recursive:true,force:true}));});
