import assert from "node:assert/strict";
import test from "node:test";
import {execFileSync} from "node:child_process";
import {mkdtempSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {Value} from "typebox/value";
import {assistedCallConfigV1Schema,validateAssistedCallConfigV1} from "../src/assisted-contracts.ts";
import {canonicalSnapshotDigestV1,navigatorReceiptV1Schema,validateNavigatorReceiptV1} from "../src/navigator-contracts.ts";

const uuid="018f22a0-7b4c-7abc-8def-0123456789ab",sha="a".repeat(64),oid="b".repeat(40);
const config={version:1,runId:uuid,callId:uuid,subject:{repositoryRoot:"/repo",github:{owner:"o",name:"r"},parentIssue:1,children:[]},acquisition:{workspaces:[{id:"w",root:"/repo",relation:"repository"}],evidence:[],labelPolicy:[]},execution:{workspaceId:"w",cwd:"/repo",role:"doctor",phase:null,environment:{inherit:true,overrides:{},unset:[]},stdin:"inherit"}};
const snapshotBase={version:1 as const,capturedAt:"2025-01-01T00:00:00.000Z",runId:uuid,subject:{repositoryRoot:"/repo",github:{owner:"o",name:"r",id:"R"},parent:{number:1,id:"I"}},children:[],parentObservation:{state:"open" as const,labels:[],observedAt:"2025-01-01T00:00:00.000Z",query:{transport:"github_rest" as const,operation:"issue"}},labelPolicy:[],workspaces:[{id:"w",root:"/repo",relation:"repository" as const,head:oid,target:oid}],evidence:[{id:"e",kind:"input" as const,sha256:sha,provenance:{kind:"declared",reference:"e"},handle:"h"}],positionCursor:0,latestAttempt:null};
const snapshot={...snapshotBase,digest:canonicalSnapshotDigestV1(snapshotBase)};
const primaryByStatus={ordinary:{kind:"stop",reasonCategory:"complete",conditions:[],hazards:[],evidenceIds:[]},insufficient:{kind:"obtain_evidence_and_reconsult",missing:[{kind:"authority",identity:"x"}],evidenceIds:[]},refused:{kind:"return_scope_or_authority_defect",defect:{category:"out_of_scope",evidenceId:"e"},evidenceIds:["e"]},escalated:{kind:"seek_owner_decision",decision:{category:"authority",question:"who?"},evidenceIds:[]}} as const;
function receipt(status:keyof typeof primaryByStatus){return{version:1,status,runId:uuid,subject:snapshot.subject,snapshotDigest:snapshot.digest,positionCursor:0,invocationId:uuid,latestAttempt:null,evidenceRead:[{evidenceId:"e",fullyRead:true}],primary:primaryByStatus[status],explanation:"x"}}
function parity(schema:unknown,value:unknown,runtime:()=>unknown,valid:boolean){assert.equal(Value.Check(schema as never,value),valid);if(valid)assert.doesNotThrow(runtime);else assert.throws(runtime)}
test("actual schema consumer and runtime accept every role/phase and Navigator status variant",()=>{for(const role of ["judge","reviewer","collector","doctor"]){const value={...config,execution:{...config.execution,role,phase:null}};parity(assistedCallConfigV1Schema,value,()=>validateAssistedCallConfigV1(value),true)}for(const role of ["coder","fixer"])for(const phase of ["plan","apply"]){const value={...config,execution:{...config.execution,role,phase}};parity(assistedCallConfigV1Schema,value,()=>validateAssistedCallConfigV1(value),true)}for(const status of Object.keys(primaryByStatus) as Array<keyof typeof primaryByStatus>){const value=receipt(status);parity(navigatorReceiptV1Schema,value,()=>validateNavigatorReceiptV1(value,snapshot,[{evidenceId:"e",fullyRead:true}]),true)}});
test("actual schema consumer and runtime reject phase, variant, and extra-property violations",()=>{const invalidConfigs=[{...config,execution:{...config.execution,role:"doctor",phase:"apply"}},{...config,execution:{...config.execution,role:"fixer",phase:null}},{...config,extra:true}];for(const value of invalidConfigs)parity(assistedCallConfigV1Schema,value,()=>validateAssistedCallConfigV1(value),false);for(const value of [{...receipt("ordinary"),status:"refused"},{...receipt("ordinary"),extra:true},{...receipt("ordinary"),primary:{...receipt("ordinary").primary,extra:true}}])parity(navigatorReceiptV1Schema,value,()=>validateNavigatorReceiptV1(value,snapshot,[{evidenceId:"e",fullyRead:true}]),false)});
test("packed cold-installed schema exports retain behavioral parity for deep and cross-variant cases",()=>{const pack=mkdtempSync(join(tmpdir(),"schema-pack-")),source=join(pack,"source"),consumer=mkdtempSync(join(tmpdir(),"schema-consumer-"));execFileSync("bash",["-c",`mkdir -p "$1" && tar --exclude=.git --exclude=node_modules --exclude=dist -cf - . | tar -xf - -C "$1" && ln -s ${JSON.stringify(join(process.cwd(),"node_modules"))} "$1/node_modules"`,"copy",source]);const tar=execFileSync("npm",["pack","--pack-destination",pack],{cwd:source,encoding:"utf8"}).trim().split("\n").at(-1)!;writeFileSync(join(consumer,"package.json"),JSON.stringify({private:true,type:"module"}));execFileSync("npm",["install","--no-audit","--no-fund",join(pack,tar),"tsx"],{cwd:consumer,stdio:"ignore"});const values=[config,{...config,subject:{...config.subject}},{...config,subject:{...config.subject,github:{...config.subject.github,extra:true}}},{...config,subject:{...config.subject,children:[{number:0,relation:"sub_issue",provenance:{kind:"x",reference:"y"}}]}},{...config,acquisition:{...config.acquisition,workspaces:[{...config.acquisition.workspaces[0],extra:true}]}},{...config,execution:{...config.execution,environment:{...config.execution.environment,extra:true}}},receipt("ordinary"),receipt("insufficient"),receipt("refused"),receipt("escalated"),{...receipt("ordinary"),latestAttempt:{}},{...receipt("ordinary"),evidenceRead:[{evidenceId:"e",fullyRead:true,extra:true}]},{...receipt("insufficient"),primary:receipt("ordinary").primary},{...receipt("refused"),primary:{...primaryByStatus.refused,defect:{...primaryByStatus.refused.defect,extra:true}}},{...receipt("escalated"),primary:{...primaryByStatus.escalated,decision:{...primaryByStatus.escalated.decision,extra:true}}}];const expected=values.map((v,i)=>i<6?Value.Check(assistedCallConfigV1Schema as never,v):Value.Check(navigatorReceiptV1Schema as never,v));writeFileSync(join(consumer,"check.mts"),`import{Value}from'typebox/value';import{assistedCallConfigV1Schema as a}from'@ak/pi-workflow-roles/src/assisted-contracts.ts';import{navigatorReceiptV1Schema as n}from'@ak/pi-workflow-roles/src/navigator-contracts.ts';const v=${JSON.stringify(values)};process.stdout.write(JSON.stringify(v.map((x,i)=>Value.Check(i<6?a:n,x))));`);const actual=JSON.parse(execFileSync(join(consumer,"node_modules/.bin/tsx"),["check.mts"],{cwd:consumer,encoding:"utf8"}));assert.deepEqual(actual,expected)});
