import assert from "node:assert/strict";
import test from "node:test";
import {Value} from "typebox/value";
import {assistedCallConfigV1Schema,validateAssistedCallConfigV1} from "../src/assisted-contracts.ts";
import {canonicalSnapshotDigestV1,navigatorReceiptV1Schema,validateNavigatorReceiptV1} from "../src/navigator-contracts.ts";

const uuid="018f22a0-7b4c-7abc-8def-0123456789ab",sha="a".repeat(64),oid="b".repeat(40);
const config={version:1,runId:uuid,callId:uuid,subject:{repositoryRoot:"/repo",github:{owner:"o",name:"r"},parentIssue:1,children:[]},acquisition:{workspaces:[{id:"w",root:"/repo",relation:"repository"}],evidence:[],labelPolicy:[]},execution:{workspaceId:"w",cwd:"/repo",role:"doctor",phase:null,environment:{inherit:true,overrides:{},unset:[]},stdin:"inherit"}};
const snapshotBase={version:1 as const,capturedAt:"2025-01-01T00:00:00.000Z",runId:uuid,subject:{repositoryRoot:"/repo",github:{owner:"o",name:"r",id:"R"},parent:{number:1,id:"I"}},children:[],parentObservation:{state:"open" as const,labels:[],observedAt:"2025-01-01T00:00:00.000Z",query:{transport:"github_rest" as const,operation:"issue"}},labelPolicy:[],workspaces:[{id:"w",root:"/repo",relation:"repository" as const,head:oid,target:oid}],evidence:[{id:"e",kind:"input" as const,sha256:sha,provenance:{kind:"declared",reference:"e"},handle:"h"}],positionCursor:0,latestAttempt:null};
const snapshot={...snapshotBase,digest:canonicalSnapshotDigestV1(snapshotBase)};
const primaryByStatus={ordinary:{kind:"stop",reasonCategory:"complete",conditions:[],hazards:[],evidenceIds:[]},insufficient:{kind:"obtain_evidence_and_reconsult",missing:[{kind:"authority",identity:"x"}],evidenceIds:[]},refused:{kind:"return_scope_or_authority_defect",defect:{category:"out_of_scope",evidenceId:"e"},evidenceIds:["e"]},escalated:{kind:"seek_owner_decision",decision:{category:"authority",question:"who?"},evidenceIds:[]}} as const;
function receipt(status:keyof typeof primaryByStatus){return{version:1,status,runId:uuid,subject:snapshot.subject,snapshotDigest:snapshot.digest,positionCursor:0,invocationId:uuid,latestAttempt:null,evidenceRead:[{evidenceId:"e",fullyRead:true}],primary:primaryByStatus[status],explanation:"x"}}
function parity(schema:unknown,value:unknown,runtime:()=>unknown,valid:boolean){assert.equal(Value.Check(schema as never,value),valid);if(valid)assert.doesNotThrow(runtime);else assert.throws(runtime)}
test("actual schema consumer and runtime accept every role/phase and Navigator status variant",()=>{for(const role of ["judge","reviewer","collector","doctor"]){const value={...config,execution:{...config.execution,role,phase:null}};parity(assistedCallConfigV1Schema,value,()=>validateAssistedCallConfigV1(value),true)}for(const role of ["coder","fixer"])for(const phase of ["plan","apply"]){const value={...config,execution:{...config.execution,role,phase}};parity(assistedCallConfigV1Schema,value,()=>validateAssistedCallConfigV1(value),true)}for(const status of Object.keys(primaryByStatus) as Array<keyof typeof primaryByStatus>){const value=receipt(status);parity(navigatorReceiptV1Schema,value,()=>validateNavigatorReceiptV1(value,snapshot,[{evidenceId:"e",fullyRead:true}]),true)}});
test("actual schema consumer and runtime reject phase, variant, and extra-property violations",()=>{const invalidConfigs=[{...config,execution:{...config.execution,role:"doctor",phase:"apply"}},{...config,execution:{...config.execution,role:"fixer",phase:null}},{...config,extra:true}];for(const value of invalidConfigs)parity(assistedCallConfigV1Schema,value,()=>validateAssistedCallConfigV1(value),false);for(const value of [{...receipt("ordinary"),status:"refused"},{...receipt("ordinary"),extra:true},{...receipt("ordinary"),primary:{...receipt("ordinary").primary,extra:true}}])parity(navigatorReceiptV1Schema,value,()=>validateNavigatorReceiptV1(value,snapshot,[{evidenceId:"e",fullyRead:true}]),false)});
test("cold built-package schema exports retain behavioral parity",async()=>{const assisted=await import(`../dist/assisted-contracts.js?cold=${Date.now()}`),navigator=await import(`../dist/navigator-contracts.js?cold=${Date.now()}`);for(const value of [config,{...config,extra:true}])assert.equal(Value.Check(assisted.assistedCallConfigV1Schema,value),Value.Check(assistedCallConfigV1Schema as never,value));for(const value of [receipt("escalated"),{...receipt("escalated"),status:"ordinary"}])assert.equal(Value.Check(navigator.navigatorReceiptV1Schema,value),Value.Check(navigatorReceiptV1Schema as never,value))});
