import type { RecorderConfig } from "./config.ts";
import type { AdmittedArtifact } from "./admit.ts";
import type { ChildOutcome } from "./errors.ts";
import { internalRecorderError } from "./errors.ts";
import type { AuditObservation, ExtractionResult } from "./extract.ts";
import { combineReports, publicRedactionReport, scanJsonValue, type ScanReport } from "./scanner.ts";
export type RecorderManifestV2={version:2;archive:RecorderConfig["archive"];invocation:{id:string};session:{id:string;directory:string;basename:string;sha256:string;byteLength:number;retention:"caller-owned-raw-not-promoted"};execution:{argv:string[];cwd:string;environment:RecorderConfig["execution"]["environment"];stdin:"inherit";stdio:{stdout:"pass-through";stderr:"pass-through";diagnosticTailBytes:4096}};provenance:RecorderConfig["provenance"]&{verification:"unverified"};artifacts:AdmittedArtifact[];receipt:{toolName:string;toolCallId:string;artifactId:"receipt";artifactKind:"acceptedReceipt"|"sanitizedDerivativeOfAcceptedReceipt"};auditObservation:AuditObservation|null;child:{status:"exited"|"signaled";exitCode:number|null;signal:string|null};recorder:{status:"completed"};redaction:{hits:Array<{ruleId:string;location:string;count:number}>}};
export function loadPublicManifestSchema(){return {$schema:"https://json-schema.org/draft/2020-12/schema",title:"Recorder manifest v2"}}
export function validatePublicManifest(v:unknown):asserts v is RecorderManifestV2{if(!v||typeof v!=="object"||Array.isArray(v)){throw internalRecorderError("manifest",new Error("manifest shape"))}const m=v as RecorderManifestV2;if(m.version!==2||m.invocation.id!==m.session.id||!m.receipt||m.execution.stdio.stdout!=="pass-through"||m.execution.stdio.diagnosticTailBytes!==4096)throw internalRecorderError("manifest",new Error("manifest invariant"));}
export function buildManifest(o:{config:RecorderConfig;childArgv:string[];artifacts:AdmittedArtifact[];extraction:ExtractionResult;child:ChildOutcome;scanReport:ScanReport;session:{id:string;directory:string;basename:string;sha256:string;byteLength:number}}):{manifest:RecorderManifestV2;report:ScanReport}{if(o.child.status==="not-spawned")throw internalRecorderError("manifest",new Error("child missing"));const skeleton:RecorderManifestV2={version:2,archive:o.config.archive,invocation:{id:o.config.session.id},session:{...o.session,retention:"caller-owned-raw-not-promoted"},execution:{argv:o.childArgv,cwd:o.config.execution.cwd,environment:o.config.execution.environment,stdin:"inherit",stdio:{stdout:"pass-through",stderr:"pass-through",diagnosticTailBytes:4096}},provenance:{...o.config.provenance,verification:"unverified"},artifacts:o.artifacts,receipt:{toolName:o.extraction.receipt.toolName,toolCallId:o.extraction.receipt.toolCallId,artifactId:"receipt",artifactKind:o.extraction.artifactKind},auditObservation:o.extraction.auditObservation,child:{status:o.child.status,exitCode:o.child.exitCode,signal:o.child.signal},recorder:{status:"completed"},redaction:{hits:[]}};const scanned=scanJsonValue(skeleton,"manifest");const report=combineReports(o.scanReport,scanned.report);const manifest=scanned.value as RecorderManifestV2;manifest.redaction.hits=publicRedactionReport(report);validatePublicManifest(manifest);return{manifest,report}}
