import {sha256Hex} from "./sha256.ts"; import type {CurrentPositionSnapshotV1} from "./navigator-contracts.ts";
export type NavigatorEvidenceRead={evidenceId:string;offset:number;byteLength:number;totalByteLength:number;content:string;truncated:boolean};
type Interval=[number,number];
function credit(intervals:Interval[],start:number,end:number){if(start===end)return;let i=0;while(i<intervals.length&&intervals[i]![1]<start)i++;while(i<intervals.length&&intervals[i]![0]<=end){start=Math.min(start,intervals[i]![0]);end=Math.max(end,intervals[i]![1]);intervals.splice(i,1)}intervals.splice(i,0,[start,end])}
function continuation(byte:number|undefined){return byte!==undefined&&(byte&0xc0)===0x80}
function sequenceEnd(bytes:Uint8Array,index:number){const first=bytes[index];if(first===undefined)return-1;if(first<=0x7f)return index+1;if(first>=0xc2&&first<=0xdf)return continuation(bytes[index+1])?index+2:-1;if(first>=0xe0&&first<=0xef){const second=bytes[index+1],validSecond=first===0xe0?second!==undefined&&second>=0xa0&&second<=0xbf:first===0xed?second!==undefined&&second>=0x80&&second<=0x9f:continuation(second);return validSecond&&continuation(bytes[index+2])?index+3:-1}if(first>=0xf0&&first<=0xf4){const second=bytes[index+1],validSecond=first===0xf0?second!==undefined&&second>=0x90&&second<=0xbf:first===0xf4?second!==undefined&&second>=0x80&&second<=0x8f:continuation(second);return validSecond&&continuation(bytes[index+2])&&continuation(bytes[index+3])?index+4:-1}return-1}
function utf8End(bytes:Uint8Array,start:number,target:number){let index=start;while(index<target){const end=sequenceEnd(bytes,index);if(end<0)return index>start?index:target;if(end>target)return index>start?index:end;index=end}return target}
export class NavigatorEvidenceStore{readonly #byId=new Map<string,{bytes:Uint8Array;read:Interval[];touched:boolean}>();constructor(evidence:CurrentPositionSnapshotV1["evidence"],handles:ReadonlyMap<string,Uint8Array>,readonly maxPageBytes=16_384){for(const item of evidence){if(this.#byId.has(item.id))throw new Error("duplicate evidence id");const source=handles.get(item.handle);if(!source)throw new Error(`missing evidence handle: ${item.id}`);const bytes=new Uint8Array(source);if(sha256Hex(bytes)!==item.sha256)throw new Error(`evidence digest mismatch: ${item.id}`);this.#byId.set(item.id,{bytes,read:[],touched:false})}}read(evidenceId:string,offset=0,limit=this.maxPageBytes):NavigatorEvidenceRead{const item=this.#byId.get(evidenceId);if(!item)throw new Error("evidence id is not admitted");if(!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1)throw new Error("invalid evidence page");if(offset>item.bytes.length)throw new Error("offset beyond evidence");const target=Math.min(offset, item.bytes.length)+Math.min(limit,this.maxPageBytes,item.bytes.length-offset),end=utf8End(item.bytes,offset,target),slice=item.bytes.subarray(offset,end);let content:string;try{content=new TextDecoder("utf-8",{fatal:true}).decode(slice)}catch{throw new Error("evidence page is not valid UTF-8")};item.touched=true;credit(item.read,offset,end);return{evidenceId,offset,byteLength:end-offset,totalByteLength:item.bytes.length,content,truncated:end<item.bytes.length}}readRecord(){return[...this.#byId].flatMap(([evidenceId,v])=>v.touched?[{evidenceId,fullyRead:v.bytes.length===0||v.read.length===1&&v.read[0]![0]===0&&v.read[0]![1]===v.bytes.length}]:[])} }
export const navigatorEvidenceReadSchema={type:"object",additionalProperties:false,required:["evidenceId"],properties:{evidenceId:{type:"string"},offset:{type:"integer",minimum:0},limit:{type:"integer",minimum:1,maximum:16384}}} as const;
