import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { REVIEWER_CHILD_TOOLS, REVIEWER_PREREQUISITES, createReviewerDispatcher, parseReviewerCapabilities, type AcceptedReviewerExecution, type ReviewerPinnedGitReader, type ReviewerProposalV1 } from "../../src/reviewer-dispatch.ts";
import { REVIEWER_STANDARDS_CONCLUSION_KEYS, reviewerAxisMethodAdapter, reviewerAxisOutputContract } from "../../src/reviewer-construction.ts";
import { reviewerPromptIdentity } from "../../src/reviewer-prompt-identity.ts";

const task = Buffer.from("opaque task\n");
const command = "git diff A...B";
const cap = parseReviewerCapabilities(Buffer.from(JSON.stringify({ version:1, taskSha256:createHash("sha256").update(task).digest("hex"), tools:[...REVIEWER_CHILD_TOOLS], prerequisiteOperations:[...REVIEWER_PREREQUISITES] })), task);
const request = { tools:["read","bash"] as const, prerequisiteOperations:[...REVIEWER_PREREQUISITES] };
const proposal: ReviewerProposalV1 = { version:1, base:{revision:"A"}, materials:[{id:"rules",repositoryPath:"RULES.md"},{id:"spec",repositoryPath:"SPEC.md"}], relevanceHints:{standards:["rules","spec"],spec:["spec","rules"]}, spec:{state:"established"}, required:{standards:request,spec:request} };
function reader(overrides: Partial<ReviewerPinnedGitReader>={}): ReviewerPinnedGitReader { return { pin:{repositoryRoot:"/r",objectFormat:"sha1",targetHead:"B",refs:{}}, async snapshot(){return this.pin}, async resolve(x){return x}, async range(base){return {base,target:"B",diffCommand:command,diffSha256:"1".repeat(64),commits:["B"]}}, async material(path){return Buffer.from(path+" bytes\n")}, ...overrides }; }
function harness(options:{reader?:ReviewerPinnedGitReader; run?:(x:AcceptedReviewerExecution)=>Promise<unknown>}={}) { let starts=0; let execution:AcceptedReviewerExecution|undefined; const dispatcher=createReviewerDispatcher({task,canonicalSkill:"### 3. Identify the standards sources\nbaseline\n### 4. Spawn both sub-agents in parallel\n**Standards sub-agent prompt**\nstandards question\n**Spec sub-agent prompt**\nspec question\n### 5. Aggregate\n",capabilities:cap,reader:options.reader??reader(),hostTools:REVIEWER_CHILD_TOOLS,async run(x){starts++;execution=x;return options.run?.(x)}}); return {dispatcher,get starts(){return starts},get execution(){return execution}}; }

test("common materials and overlapping relevance hints are legal and available to both legs",async()=>{const h=harness();const r=await h.dispatcher.propose(proposal);assert.equal(r.status,"accepted");if(r.status!=="accepted")return;assert.deepEqual(r.dispatch.materials.map(x=>x.id),["rules","spec"]);assert.deepEqual(r.dispatch.relevanceHints,proposal.relevanceHints);assert.equal(r.dispatch.legs.length,2);assert.deepEqual(h.execution?.bundle,r.dispatch.bundle);});
test("one and two clone dispatches carry byte-identical deterministic bundles",async()=>{const a=harness(),b=harness();const two=await a.dispatcher.propose(proposal);const one=await b.dispatcher.propose({...proposal,relevanceHints:{standards:["rules"]},spec:{state:"not-established"},required:{standards:request}});assert.equal(two.status,"accepted");assert.equal(one.status,"accepted");if(two.status==="accepted"&&one.status==="accepted"){assert.deepEqual(two.dispatch.bundle,one.dispatch.bundle);assert.equal(one.dispatch.legs.length,1);}});
test("axis adapters compile deterministic distinct single-axis prompt identities without changing common bytes",async()=>{const a=harness(),b=harness();const first=await a.dispatcher.propose(proposal),second=await b.dispatcher.propose(proposal);assert.equal(first.status,"accepted");assert.equal(second.status,"accepted");if(first.status!=="accepted"||second.status!=="accepted")return;assert.deepEqual(first.dispatch.legs,second.dispatch.legs);const [standards,spec]=first.dispatch.legs;assert.notEqual(standards!.prompt.sha256,spec!.prompt.sha256);const three=[...REVIEWER_STANDARDS_CONCLUSION_KEYS];assert.deepEqual(reviewerAxisOutputContract("standards"),{axis:"standards",requiredConclusions:three,excludedConclusions:[]});assert.deepEqual(reviewerAxisOutputContract("spec"),{axis:"spec",requiredConclusions:[],excludedConclusions:three});assert.equal(standards!.prompt.text.includes(reviewerAxisMethodAdapter("standards")),true);assert.equal(spec!.prompt.text.includes(reviewerAxisMethodAdapter("spec")),true);assert.match(standards!.prompt.text,/Answer only the canonical Standards question/);assert.doesNotMatch(standards!.prompt.text,/Do not emit a Spec assessment|finding count/);assert.match(spec!.prompt.text,/Answer only the canonical Spec question/);assert.doesNotMatch(spec!.prompt.text,/Do not emit a Standards assessment|finding count/);for(const leg of first.dispatch.legs){assert.match(leg.prompt.text,/canonical Skill snapshot.*authoritative semantic input/);assert.match(leg.prompt.text,/may read and cite any supplied common material/);assert.match(leg.prompt.text,/bytes are preserved verbatim; no heading parser, sanitizer, section splitter/);}assert.deepEqual(first.dispatch.bundle.entries,second.dispatch.bundle.entries);assert.equal(first.dispatch.bundle.entries.find(x=>x.id==="canonical-skill")!.bytes,"### 3. Identify the standards sources\nbaseline\n### 4. Spawn both sub-agents in parallel\n**Standards sub-agent prompt**\nstandards question\n**Spec sub-agent prompt**\nspec question\n### 5. Aggregate\n");});
test("prompts contain path and digest references but no material, task, baseline, or commit transcription",async()=>{const h=harness();const r=await h.dispatcher.propose(proposal);assert.equal(r.status,"accepted");if(r.status!=="accepted")return;for(const leg of r.dispatch.legs){assert.match(leg.prompt.text,/relativeClonePath.*sha256/);assert.doesNotMatch(leg.prompt.text,/RULES\.md bytes|opaque task\n|baseline\n|Commits:/);}assert.notEqual(r.dispatch.input.canonicalSkill.sha256,r.dispatch.input.construction.implementationSha256);});
test("dangling advisory hints are accepted while duplicate material identities and target drift reject before provider start",async()=>{const hinted=harness();assert.equal((await hinted.dispatcher.propose({...proposal,relevanceHints:{standards:["missing"]}})).status,"accepted");assert.equal(hinted.starts,1);const duplicate=harness();assert.equal((await duplicate.dispatcher.propose({...proposal,materials:[proposal.materials[0]!,proposal.materials[0]!]})).status,"rejected");assert.equal(duplicate.starts,0);const drift=harness({reader:reader({async snapshot(){return {repositoryRoot:"/r",objectFormat:"sha1",refs:{},targetHead:"C"}}})});assert.equal((await drift.dispatcher.propose(proposal)).status,"rejected");assert.equal(drift.starts,0);});
test("dispatcher preserves prompt constraint diagnostics while ledger evidence stays typed",async()=>{const decisions:any[]=[];let pass=0;const dispatcher=createReviewerDispatcher({task,canonicalSkill:"skill",capabilities:cap,reader:reader(),hostTools:REVIEWER_CHILD_TOOLS,compilePrompt(text){return reviewerPromptIdentity(`${text}${++pass===1?"":"changed"}`)},decisionEvidence:decision=>decisions.push(decision),async run(){throw new Error("must not run")}});const result=await dispatcher.propose({...proposal,spec:{state:"not-established"},required:{standards:request}});assert.equal(result.status,"rejected");if(result.status!=="rejected")return;assert.match(result.diagnostic,/repeated prompt compilation/);assert.deepEqual(decisions,[{disposition:"rejected",identity:result.identity,violations:["prompt-identity-mismatch"],started:false}]);});
test("runtime derives the sole bash command from the pinned range",async()=>{assert.throws(()=>parseReviewerCapabilities(Buffer.from(JSON.stringify({version:1,taskSha256:"0".repeat(64),tools:[],prerequisiteOperations:[]})),task));const h=harness();const result=await h.dispatcher.propose(proposal);assert.equal(result.status,"accepted");assert.deepEqual(h.execution?.legs.map(leg=>leg.grant.bashCommands),[[command],[command]]);assert.equal(JSON.stringify(cap).includes(command),false);assert.equal(JSON.stringify(proposal).includes(command),false);});
test("acceptance is irreversible and concurrent proposals start exactly once",async()=>{let release!:()=>void;const gate=new Promise<void>(r=>release=r);let entered=0;const rd=reader({async range(base){entered++;await gate;return {base,target:"B",diffCommand:command,diffSha256:"1".repeat(64),commits:["B"]}}});const h=harness({reader:rd});const x=h.dispatcher.propose(proposal),y=h.dispatcher.propose(proposal);while(entered<2)await new Promise(r=>setImmediate(r));release();assert.deepEqual((await Promise.all([x,y])).map(x=>x.status).sort(),["accepted","closed"]);assert.equal(h.starts,1);});
